### ISSUE TITLE
Fix doctest example in homework 1

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/cis194-templates#2]
The doctest example for the `hanoi` function in homework 1 has some spaces that must be removed:

``` haskell
-- >>> hanoi 2 "a" "b" "c"
-- [("a","c"), ("a","b"), ("c","b")]
```

Should be:

``` haskell
-- >>> hanoi 2 "a" "b" "c"
-- [("a","c"),("a","b"),("c","b")]
```

@CristhianMotoche Can you fix this one? I think it's the only problem regarding this homework.

**Comment by CristhianMotoche** [comment]
I'll do it now.

**Comment by CristhianMotoche** [comment]
Thanks @jpvillaisaza

**Comment by jpvillaisaza** [comment]
@CristhianMotoche Thanks!
